# Generated by Django 4.1.7 on 2023-10-15 12:37

from django.db import migrations, models
import things.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.CharField(blank=True, max_length=121),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='password',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='quantity',
            field=models.IntegerField(validators=[things.models.Thing.validate_quantity_range]),
        ),
        migrations.AlterField(
            model_name='thing',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
